# Generated by Django 4.0.10 on 2023-07-05 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='total_page',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_books', models.ManyToManyField(related_name='finished_users', to='base.readingstatus')),
                ('reading_books', models.ManyToManyField(related_name='reading_users', to='base.readingstatus')),
                ('to_read_books', models.ManyToManyField(related_name='to_read_users', to='base.readingstatus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='readingstatus',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.book'),
        ),
        migrations.AddField(
            model_name='readingstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
